package com.sample

import org.domain.workshop.entity.*


rule "Prueba"
	when
		$orderinfo: Orderinfo(datePlaced != null )
	then
		System.out.println( "Regla de Prueba --> Aplicación Web" );
		System.out.println( $orderinfo.getCustomer().getGold() );
		System.out.println( $orderinfo.getCustomer().getSilver() );
end

rule "Descuento"
 no-loop true
dialect "mvel"
 when
	$customer : Customer( gold == "1" )
 	$orderinfo : Orderinfo( total > "200" , customerId  == $customer.customerId )
then
	$orderinfo.setDiscount( 12 );
update( $orderinfo );
		System.out.println( "Regla de Descuento" );
end






rule "Mayor 100"
dialect "mvel" 
when 
		$orderinfo: Orderinfo(total > 100 )
then
		$discount = new java.math.BigDecimal(1.00)
		$orderinfo.discount = $orderinfo.discount + $discount
		System.out.println( "Descuento por mayor a 100" );  
end


rule "Cliente GOLD"
dialect "mvel" 
when 	
		Customer($customerId: customerId ,  gold =="1")
		$orderinfo: Orderinfo(customerId == $customerId  )
		
then
		$discount = new java.math.BigDecimal(100.00)		
		$orderinfo.discount = $orderinfo.discount + $discount
		System.out.println( "Cliente Gold" );
end


rule "Cantidad de Items"
dialect "mvel" 
when 	
		$orderinfo: Orderinfo($orderlines : orderlines)
		$orderline : Orderline(quantity  > 10) from $orderlines
then
		$discount = new java.math.BigDecimal(1.5)		
		$orderinfo.discount = $orderinfo.discount + $discount
		System.out.println( "Mas de 10 Items de un tipo" );
end


rule "Cliente Silver"
dialect "mvel" 
when 
		Customer(silver == "1")
then
		System.out.println( "Cliente Silver" );
end
