package org.domain.workshop.entity;
// Generated Jan 2, 2012 3:00:03 PM by Hibernate Tools 3.4.0.CR1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Barcode generated by hbm2java
 */
@Entity
@Table(name="barcode"
)
public class Barcode  implements java.io.Serializable {


     private String barcodeEan;
     private int itemId;

    public Barcode() {
    }

    public Barcode(String barcodeEan, int itemId) {
       this.barcodeEan = barcodeEan;
       this.itemId = itemId;
    }
   
     @Id 

    
    @Column(name="barcode_ean", unique=true, nullable=false, length=13)
    @NotNull
    @Length(max=13)
    public String getBarcodeEan() {
        return this.barcodeEan;
    }
    
    public void setBarcodeEan(String barcodeEan) {
        this.barcodeEan = barcodeEan;
    }

    
    @Column(name="item_id", nullable=false)
    public int getItemId() {
        return this.itemId;
    }
    
    public void setItemId(int itemId) {
        this.itemId = itemId;
    }




}


