package org.domain.workshop.entity;

// Generated Jan 2, 2012 3:00:03 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;
import org.jboss.seam.annotations.Name;

/**
 * Item generated by hbm2java
 */
@Entity
@Table(name = "item")
@Name("item")
public class Item implements java.io.Serializable {

	private int itemId;
	private String description;
	private BigDecimal costPrice;
	private BigDecimal sellPrice;
	private int points;
	private char offer;
	
	

	//Custom
	



	public Item() {
	}

	public Item(int itemId, String description, int points, char offer) {
		this.itemId = itemId;
		this.description = description;
		this.points = points;
		this.offer = offer;
	}

	public Item(int itemId, String description, BigDecimal costPrice,
			BigDecimal sellPrice, int points, char offer) {
		this.itemId = itemId;
		this.description = description;
		this.costPrice = costPrice;
		this.sellPrice = sellPrice;
		this.points = points;
		this.offer = offer;
	}

	@Id
	@Column(name = "item_id", unique = true, nullable = false)
	public int getItemId() {
		return this.itemId;
	}

	public void setItemId(int itemId) {
		this.itemId = itemId;
	}

	@Column(name = "description", nullable = false, length = 64)
	@NotNull
	@Length(max = 64)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "cost_price", precision = 7)
	public BigDecimal getCostPrice() {
		return this.costPrice;
	}

	public void setCostPrice(BigDecimal costPrice) {
		this.costPrice = costPrice;
	}

	@Column(name = "sell_price", precision = 7)
	public BigDecimal getSellPrice() {
		return this.sellPrice;
	}

	public void setSellPrice(BigDecimal sellPrice) {
		this.sellPrice = sellPrice;
	}

	@Column(name = "points", nullable = false)
	public int getPoints() {
		return this.points;
	}

	public void setPoints(int points) {
		this.points = points;
	}

	@Column(name = "offer", nullable = false, length = 1)
	public char getOffer() {
		return this.offer;
	}

	public void setOffer(char offer) {
		this.offer = offer;
	}
	


}
