package org.domain.workshop.entity;

// Generated Jan 2, 2012 3:00:03 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;

/**
 * OrderlineId generated by hbm2java
 */
@Embeddable
public class OrderlineId implements java.io.Serializable {

	private int orderinfoId;
	private int itemId;
	

	

	public OrderlineId() {
	}

	public OrderlineId(int orderinfoId, int itemId) {
		this.orderinfoId = orderinfoId;
		this.itemId = itemId;
	}

	@Column(name = "orderinfo_id", nullable = false)
	public int getOrderinfoId() {
		return this.orderinfoId;
	}

	public void setOrderinfoId(int orderinfoId) {
		this.orderinfoId = orderinfoId;
	}

	@Column(name = "item_id", nullable = false)
	public int getItemId() {
		return this.itemId;
	}

	public void setItemId(int itemId) {
		this.itemId = itemId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof OrderlineId))
			return false;
		OrderlineId castOther = (OrderlineId) other;

		return (this.getOrderinfoId() == castOther.getOrderinfoId())
				&& (this.getItemId() == castOther.getItemId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getOrderinfoId();
		result = 37 * result + this.getItemId();
		return result;
	}

	


}
