package org.domain.workshop.entity;

// Generated Jan 2, 2012 3:00:03 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;
import org.jboss.seam.annotations.Name;

/**
 * Orderinfo generated by hbm2java
 */
@Entity
@Table(name = "orderinfo")
@Name("orderInfo")
public class Orderinfo implements java.io.Serializable {

	private int orderinfoId;
	private int customerId;
	private Date datePlaced;
	private Date dateShipped;
	private Date arrivalDate;
	
	private Customer customer;


	private BigDecimal shipping;
	private BigDecimal total;
	private BigDecimal discount;

	private String comment;
	
	Set<Orderline> orderlines = new HashSet<Orderline>(0);



	public Orderinfo() {
	}

	public Orderinfo(int orderinfoId, int customerId, Date datePlaced) {
		this.orderinfoId = orderinfoId;
		this.customerId = customerId;
		this.datePlaced = datePlaced;
	}

	public Orderinfo(int orderinfoId, int customerId, Date datePlaced,
			Date dateShipped, BigDecimal shipping, String comment) {
		this.orderinfoId = orderinfoId;
		this.customerId = customerId;
		this.datePlaced = datePlaced;
		this.dateShipped = dateShipped;
		this.shipping = shipping;
		this.comment = comment;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "orderinfo_id", unique = true, nullable = false)
	public int getOrderinfoId() {
		return this.orderinfoId;
	}

	public void setOrderinfoId(int orderinfoId) {
		this.orderinfoId = orderinfoId;
	}

	@Column(name = "customer_id",  insertable=false, updatable=false)
	public int getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(int customerId) {
		this.customerId = customerId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_placed", nullable = false, length = 13)
	@NotNull
	public Date getDatePlaced() {
		return this.datePlaced;
	}

	public void setDatePlaced(Date datePlaced) {
		this.datePlaced = datePlaced;
	}
	
	@Temporal(TemporalType.DATE)
	@Column(name = "arrival_date", nullable = false, length = 13)
	@NotNull
	public Date getArrivalDate() {
		return arrivalDate;
	}

	public void setArrivalDate(Date arrivalDate) {
		this.arrivalDate = arrivalDate;
	}
	

	@Temporal(TemporalType.DATE)
	@Column(name = "date_shipped", length = 13)
	public Date getDateShipped() {
		return this.dateShipped;
	}

	public void setDateShipped(Date dateShipped) {
		this.dateShipped = dateShipped;
	}

	@Column(name = "shipping", precision = 7)
	public BigDecimal getShipping() {
		return this.shipping;
	}

	public void setShipping(BigDecimal shipping) {
		this.shipping = shipping;
	}

	@Column(name = "total", precision = 7)
	public BigDecimal getTotal() {
		return total;
	}

	public void setTotal(BigDecimal total) {
		this.total = total;
	}

	
	@Column(name = "discount", precision = 7)
	public BigDecimal getDiscount() {
		return discount;
	}

	public void setDiscount(BigDecimal discount) {
		this.discount = discount;
	}

	
	@Column(name = "comment", length = 200)
	@Length(max = 200)
	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "orderinfo" , cascade = CascadeType.ALL ) 
	public Set<Orderline> getOrderlines() {
		return orderlines;
	}

	public void setOrderlines(Set<Orderline> orderlines) {
		this.orderlines = orderlines;
	}
	
	
	@OneToOne(fetch = FetchType.LAZY )
	@JoinColumn(name="customer_id")
	public Customer getCustomer() {
		return customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}
	

}
