package org.domain.workshop.entity;

// Generated Jan 2, 2012 3:00:03 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import org.hibernate.validator.NotNull;

/**
 * Orderline generated by hbm2java
 */
@Entity
@Table(name = "orderline")
public class Orderline implements java.io.Serializable {

	private OrderlineId id;
	private int quantity;
	private Item item;
	
 
	private Orderinfo orderinfo;


	public Orderline() {
	}

	public Orderline(OrderlineId id, int quantity) {
		this.id = id;
		this.quantity = quantity;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "orderinfoId", column = @Column(name = "orderinfo_id", nullable = false)),
			@AttributeOverride(name = "itemId", column = @Column(name = "item_id", nullable = false)) })
	@NotNull		
	public OrderlineId getId() {
		return this.id;
	}

	public void setId(OrderlineId id) {
		this.id = id;
	}

	@Column(name = "quantity", nullable = false)
	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}
	


	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "orderinfo_id", nullable = false , insertable=false, updatable=false)
	public Orderinfo getOrderinfo() {
		return orderinfo;
	}

	public void setOrderinfo(Orderinfo orderinfo) {
		this.orderinfo = orderinfo;
	}
	
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "item_id", nullable = false , insertable=false, updatable=false)
	public Item getItem() {
		return item;
	}

	public void setItem(Item item) {
		this.item = item;
	}


}
