package org.domain.workshop.entity;

// Generated Jan 2, 2012 3:00:03 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Stock generated by hbm2java
 */
@Entity
@Table(name = "stock")
public class Stock implements java.io.Serializable {

	private int itemId;
	private int quantity;

	public Stock() {
	}

	public Stock(int itemId, int quantity) {
		this.itemId = itemId;
		this.quantity = quantity;
	}

	@Id
	@Column(name = "item_id", unique = true, nullable = false)
	public int getItemId() {
		return this.itemId;
	}

	public void setItemId(int itemId) {
		this.itemId = itemId;
	}

	@Column(name = "quantity", nullable = false)
	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

}
